Job/urls.py
from django.urls import path , include 
from . import views
from . import api
app_name = 'Job'
urlpatterns = [
    path('' ,views.jobs , name='job_list'),
    path('add' ,views.add_job , name='add_job'),
    path('<str:slug>' ,views.job_detail , name='job_detail'),
    
    # api 
    path('api/jobs' ,api.jobapi , name='jobapi'),
    path('api/jobs/<int:id>' ,api.api_detail_api , name='api_detail_api'),

    path('api/v2/jobs' ,api.joblistapi.as_view() , name='joblistapi'),
    path('api/v2/jobs/<int:id>' ,api.jobdetail.as_view() , name='jobdetail'),

]

accounts/urls.py
from django.urls import path , include 
from . import views

app_name = 'Job'

urlpatterns = [
    path('signup' ,views.signup , name='signup'),
    path('Profile' ,views.Profile , name='Profile'),
    path('profile/edit' ,views.profile_edit , name='Profile_edit'),
]

contact/urls.py
from django.urls import path , include 
from . import views

app_name = 'contact'
urlpatterns = [
    path('' ,views.send_message , name='contact'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin 
from django.urls import path , include 
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),

    path('admin/', admin.site.urls),
    path('jobs/', include('Job.urls',namespace='jobs')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%} ">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'%}">

    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- <link rel="stylesheet" href="css/responsive.css'%}"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="{% url 'jobs:job_list' %}">
                                        <img src="{% static 'img/logo.png' %}" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'jobs:job_list' %}">home</a></li>
                                            <li><a href="{% url 'jobs:job_list' %}">Browse Job</a></li>
                                            <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                                            {% if request.user.is_authenticated %}
                                            <li>
                                                <a href="{% url 'accounts:Profile'%}">Profile</a>
                                            </li>
                                            {% else %}
                                            <li>
                                                <a href="{% url 'login'%}">Log in</a>
                                            </li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{%url 'jobs:add_job'%}">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    {% block body %}


    {% endblock body %}
    

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                abdoabass400@gmail.com <br>
                                +20 100 7582 994 <br>
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="https://www.facebook.com/abdo.abass.142">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://twitter.com/Abdlrahman_Abas">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.instagram.com/abdoabass1/">
                                            <i class="fa fa-instagram"></i>
                                            
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.linkedin.com/in/abdelrahman-abass-b82904220/">
                                            <i class="fa fa-linkedin"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="https://www.linkedin.com/in/abdelrahman-abass-b82904220/">About </a></li>
                                <li><a href="https://www.linkedin.com/in/abdelrahman-abass-b82904220/">Pricing</a></li>
                                <li><a href="https://www.linkedin.com/in/abdelrahman-abass-b82904220/">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="https://github.com/abdd01">Design & Art</a></li>
                                <li><a href="https://github.com/abdd01">Engineering</a></li>
                                <li><a href="https://github.com/abdd01">Sales & Marketing</a></li>
                                <li><a href="https://github.com/abdd01">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
    
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'js/ajax-form.js'%}"></script>
    <script src="{% static 'js/waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{% static 'js/scrollIt.js'%}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/nice-select.min.js'%}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>
    <!-- <script src={% static 'js/gijgo.min.js{% static '></script> -->
    <script src={% static 'js/range.js'%}></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js'%}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{% static 'js/jquery.form.js'%}"></script>
    <script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/main.js' %}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>

templates/base_generic.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    {% load static %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    
                    
                    <div class="apply_job_form white-bg">
                        {% block content %}


                        {% endblock%}
                    </div>
                </div>
                <div class="col-lg-4 mx-auto">
                    
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }
                              
                            </script>                            
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}